### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by NyxCode** [richardwilkes/webapp#3]
Hey, really like this project! It's the only binding to CEF which just .. works.
Have you considered supported linux? I tried my luck with xcb ([xgb](https://github.com/BurntSushi/xgb)), but I'm stuck with white windows which refuse to render.

**Comment by richardwilkes** [comment]
I've looked at it briefly, but the amount of work involved is significant and I have no personal use case for it, so am unlikely to do it. Sorry.

**Comment by NyxCode** [comment]
that's unfortunate :wink: 
I'll try to get it working, but i'm pretty inexperienced in this area, so yeah, we'll see!
